services:
  mongodb:
    image: mongo:6.0
    container_name: medsupply_mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command: ['--replSet', 'rs0', '--bind_ip_all']
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--quiet',
          '--eval',
          "try { rs.status().ok } catch (e) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}).ok }",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    container_name: medsupply_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: medsupply_mailpit
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: medsupply_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:
  minio_data:
