import helmet from 'helmet';
import type { NextFunction, Request, Response } from 'express';
import { isProduction } from '../env';

/**
 * Secure HTTP response headers.
 *
 * The API returns JSON to two first-party clients and, at three endpoints, HTML
 * or a PDF that a browser renders directly: the invoice and receipt print
 * layouts and the API reference. Those are the reason a content security policy
 * matters here at all — everything else is `application/json`, which a browser
 * will not execute.
 *
 * The policy is deliberately strict and self-contained: no external origin may
 * supply a script, style, font or frame, so nothing this API serves can be
 * turned into a delivery vehicle by a compromised third-party host.
 */
export function securityHeaders() {
  const helmetMiddleware = helmet({
    contentSecurityPolicy: {
      useDefaults: false,
      directives: {
        'default-src': ["'none'"],
        // The print layouts and the API reference inline their own styles and
        // one script; both are generated by this server from data it controls.
        'script-src': ["'self'", "'unsafe-inline'"],
        'style-src': ["'self'", "'unsafe-inline'"],
        'img-src': ["'self'", 'data:', 'blob:'],
        'font-src': ["'self'", 'data:'],
        'connect-src': ["'self'"],
        'object-src': ["'none'"],
        'base-uri': ["'none'"],
        'form-action': ["'self'"],
        'frame-ancestors': ["'none'"],
        ...(isProduction ? { 'upgrade-insecure-requests': [] } : {}),
      },
    },
    // Responses are consumed cross-origin by the web application and the mobile
    // client, so the isolation headers that would block those are relaxed while
    // the ones that only affect embedding are kept.
    crossOriginEmbedderPolicy: false,
    crossOriginResourcePolicy: { policy: 'cross-origin' },
    crossOriginOpenerPolicy: { policy: 'same-origin' },
    referrerPolicy: { policy: 'no-referrer' },
    // A year, with subdomains, and preload-eligible. Only sent over TLS by
    // helmet's own logic, so a plain-HTTP development server is unaffected.
    hsts: { maxAge: 31_536_000, includeSubDomains: true, preload: true },
    frameguard: { action: 'deny' },
    noSniff: true,
    xssFilter: true,
    hidePoweredBy: true,
  });

  return (req: Request, res: Response, next: NextFunction) => {
    helmetMiddleware(req, res, (error?: unknown) => {
      if (error) return next(error);
      // Locks down the browser features this API never needs, which limits what
      // an injected script could reach if the policy above were ever bypassed.
      res.setHeader(
        'Permissions-Policy',
        'accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()',
      );
      // Nothing this API returns should be stored by a shared cache: almost all
      // of it is scoped to one signed-in actor.
      if (!res.getHeader('Cache-Control')) {
        res.setHeader('Cache-Control', 'no-store');
      }
      next();
    });
  };
}
