/**
 * The burn-down lists for `routeCoverage.test.ts`.
 *
 * Every entry is an endpoint this project ships without the corresponding
 * guarantee. They are written out one by one, rather than summarised as a
 * percentage, because a percentage hides *which* endpoints are unguarded — and
 * the endpoint that mattered here was `POST /api/v1/users`, whose role bug
 * survived twelve phases precisely because nothing called it.
 *
 * The rules that make these lists useful:
 *
 *   - Adding an entry is a deliberate act, reviewed like any other change.
 *   - Removing an entry is automatic: the moment a route becomes covered, the
 *     test fails on the stale waiver until it is struck off. The list can
 *     therefore only shrink, which is the whole point.
 *
 * At the time of writing: 150 routes, 69 covered by an integration test.
 */

/**
 * Served, but absent from the OpenAPI document.
 *
 * 91 of 150. The document was hand-declared alongside the routers rather
 * than reflected off them, so it drifted; the reconciliation test now makes any
 * further drift fail the build.
 */
export const UNDOCUMENTED_ROUTES: readonly string[] = [
  'delete /api/v1/notifications/devices',
  'delete /api/v1/orders/drafts/:id',
  'get /api/v1/activity/timeline',
  'get /api/v1/admin/audit/actions',
  'get /api/v1/admin/users/:id',
  'get /api/v1/approvals/:id',
  'get /api/v1/deliveries/:id',
  'get /api/v1/deliveries/order/:orderId',
  'get /api/v1/deliveries/personnel',
  'get /api/v1/deliveries/proof/:fileId',
  'get /api/v1/docs',
  'get /api/v1/docs/openapi.json',
  'get /api/v1/finance/my/collections',
  'get /api/v1/finance/my/invoices',
  'get /api/v1/finance/my/statement',
  'get /api/v1/finance/my/summary',
  'get /api/v1/finance/reconciliation/:shopId',
  'get /api/v1/finance/reports/collections',
  'get /api/v1/finance/reports/outstanding',
  'get /api/v1/finance/reports/overdue',
  'get /api/v1/finance/reports/summary',
  'get /api/v1/finance/shops/:shopId/invoices',
  'get /api/v1/finance/shops/:shopId/ledger',
  'get /api/v1/finance/shops/:shopId/summary',
  'get /api/v1/fulfilment/picking/:id',
  'get /api/v1/fulfilment/ready',
  'get /api/v1/inventory/batches/:id',
  'get /api/v1/inventory/medicines/:id',
  'get /api/v1/notifications/:id/deliveries',
  'get /api/v1/notifications/catalogue',
  'get /api/v1/notifications/preferences',
  'get /api/v1/notifications/unread-count',
  'get /api/v1/orders/:id',
  'get /api/v1/payments',
  'get /api/v1/payments/:id',
  'get /api/v1/payments/:id/attachment',
  'get /api/v1/payments/:id/receipt',
  'get /api/v1/payments/my-collections',
  'get /api/v1/reports/stock-movements',
  'get /api/v1/returns/:id',
  'get /api/v1/returns/credit-notes/:id',
  'get /api/v1/shops/:id',
  'get /api/v1/shops/my',
  'get /api/v1/users/me',
  'patch /api/v1/inventory/batches/:id/block',
  'patch /api/v1/inventory/medicines/:id',
  'patch /api/v1/orders/drafts/:id',
  'patch /api/v1/shops/:id',
  'patch /api/v1/shops/:id/status',
  'post /api/v1/admin/users/:id/revoke-sessions',
  'post /api/v1/approvals/:id/clarify',
  'post /api/v1/approvals/:id/hold',
  'post /api/v1/approvals/:id/start',
  'post /api/v1/deliveries/:id/acknowledge',
  'post /api/v1/deliveries/:id/arrived',
  'post /api/v1/deliveries/:id/cancel',
  'post /api/v1/deliveries/:id/handover',
  'post /api/v1/deliveries/:id/pickup',
  'post /api/v1/deliveries/:id/returned',
  'post /api/v1/deliveries/:id/returning',
  'post /api/v1/deliveries/:id/send-otp',
  'post /api/v1/deliveries/:id/start',
  'post /api/v1/finance/credit-reservations/backfill',
  'post /api/v1/finance/reconciliation/:shopId/repair',
  'post /api/v1/fulfilment/picking/:id/discrepancies',
  'post /api/v1/fulfilment/picking/:id/discrepancies/resolve',
  'post /api/v1/fulfilment/picking/:id/progress',
  'post /api/v1/fulfilment/picking/:id/resume',
  'post /api/v1/fulfilment/picking/:id/start',
  'post /api/v1/inventory/allocations/reserve',
  'post /api/v1/inventory/batches/:id/adjust',
  'post /api/v1/inventory/batches/:id/operations',
  'post /api/v1/notifications/archive',
  'post /api/v1/notifications/devices',
  'post /api/v1/notifications/read',
  'post /api/v1/notifications/read-all',
  'post /api/v1/notifications/test',
  'post /api/v1/orders/:id/duplicate',
  'post /api/v1/orders/drafts',
  'post /api/v1/orders/drafts/:id/submit',
  'post /api/v1/payments/:id/fail',
  'post /api/v1/payments/:id/handover',
  'post /api/v1/returns/:id/cancel',
  'post /api/v1/returns/:id/collect',
  'post /api/v1/returns/:id/reject',
  'post /api/v1/returns/:id/review',
  'post /api/v1/settings/:group/reset',
  'post /api/v1/shops/:id/assign-manager',
  'post /api/v1/shops/:id/assign-owner',
  'put /api/v1/notifications/preferences',
];

/**
 * Served, but no integration test reaches them.
 *
 * 81 of 150. Recorded live by `routeCoverageRecorder()` rather than inferred
 * from test source, so a test that merely mentions a path in a string does not
 * count as covering it.
 */
export const UNTESTED_ROUTES: readonly string[] = [
  'delete /api/v1/orders/drafts/:id',
  'get /api/v1/activity',
  'get /api/v1/admin/users/:id',
  'get /api/v1/approvals/:id',
  'get /api/v1/approvals/queue',
  'get /api/v1/deliveries',
  'get /api/v1/deliveries/:id',
  'get /api/v1/deliveries/personnel',
  'get /api/v1/deliveries/proof/:fileId',
  'get /api/v1/finance/my/collections',
  'get /api/v1/finance/my/invoices',
  'get /api/v1/finance/my/statement',
  'get /api/v1/finance/my/summary',
  'get /api/v1/finance/reconciliation/:shopId',
  'get /api/v1/finance/reports/collections',
  'get /api/v1/finance/reports/outstanding',
  'get /api/v1/finance/reports/overdue',
  'get /api/v1/finance/reports/summary',
  'get /api/v1/finance/shops/:shopId/invoices',
  'get /api/v1/finance/shops/:shopId/ledger',
  'get /api/v1/fulfilment/picking/:id',
  'get /api/v1/fulfilment/queue',
  'get /api/v1/inventory/batches',
  'get /api/v1/inventory/batches/:id',
  'get /api/v1/inventory/medicines',
  'get /api/v1/inventory/medicines/:id',
  'get /api/v1/inventory/movements',
  'get /api/v1/notifications/:id/deliveries',
  'get /api/v1/notifications/catalogue',
  'get /api/v1/notifications/preferences',
  'get /api/v1/orders/:id',
  'get /api/v1/payments',
  'get /api/v1/payments/:id',
  'get /api/v1/payments/:id/attachment',
  'get /api/v1/payments/my-collections',
  'get /api/v1/reports/deliveries',
  'get /api/v1/reports/orders',
  'get /api/v1/reports/returns',
  'get /api/v1/reports/sales/breakdown',
  'get /api/v1/reports/stock-movements',
  'get /api/v1/returns/:id',
  'get /api/v1/returns/credit-notes/:id',
  'get /api/v1/shops/:id',
  'get /api/v1/shops/my',
  'get /health',
  'get /health/ready',
  'get /health/version',
  'patch /api/v1/inventory/batches/:id/block',
  'patch /api/v1/inventory/medicines/:id',
  'patch /api/v1/orders/drafts/:id',
  'patch /api/v1/shops/:id',
  'patch /api/v1/shops/:id/status',
  'post /api/v1/admin/users/:id/revoke-sessions',
  'post /api/v1/approvals/:id/clarify',
  'post /api/v1/approvals/:id/hold',
  'post /api/v1/approvals/:id/reject',
  'post /api/v1/auth/logout',
  'post /api/v1/auth/logout-all',
  'post /api/v1/deliveries/:id/cancel',
  'post /api/v1/finance/adjustments',
  'post /api/v1/finance/reconciliation/:shopId/repair',
  'post /api/v1/inventory/allocations/reserve',
  'post /api/v1/inventory/batches/:id/adjust',
  'post /api/v1/inventory/batches/:id/operations',
  'post /api/v1/inventory/batches/receive',
  'post /api/v1/inventory/medicines',
  'post /api/v1/notifications/archive',
  'post /api/v1/notifications/read-all',
  'post /api/v1/orders/:id/duplicate',
  'post /api/v1/orders/drafts',
  'post /api/v1/orders/drafts/:id/submit',
  'post /api/v1/payments/:id/fail',
  'post /api/v1/returns/:id/collect',
  'post /api/v1/returns/:id/reject',
  'post /api/v1/returns/:id/review',
  'post /api/v1/shops',
  'post /api/v1/shops/:id/assign-manager',
  'post /api/v1/shops/:id/assign-owner',
  'post /api/v1/users',
];
